<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="Yiwei Liao" />


<title>Ethereum Analysis</title>

<script src="CMSC320_Final_project_files/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="CMSC320_Final_project_files/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="CMSC320_Final_project_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="CMSC320_Final_project_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="CMSC320_Final_project_files/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="CMSC320_Final_project_files/navigation-1.1/tabsets.js"></script>
<link href="CMSC320_Final_project_files/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="CMSC320_Final_project_files/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>



<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Ethereum Analysis</h1>
<h4 class="author">Yiwei Liao</h4>
<h4 class="date">5/21/2019</h4>

</div>


<p>##INTRODUCTION Even though the cryptocurrency faze has gone, cryptocurrency trading is still a hot topic. Especially Ethereum, one of the soundest projects in the whole cryptocurrency world. Ethereum is not just a platform but also a programming language (Turing complete) running on a blockchain, helping developers to build and publish distributed applications.</p>
<p>The purpose of this tutorial is to examine daily market value of cryptocurrency Ethereum and determine if we can form any predictions and correctly hypothesize based on the data.</p>
<p>##GATHERING DATA The first step is downloading and importing the data that we will be analyzing. Download the dataset from the link: <a href="https://www.kaggle.com/jessevent/all-crypto-currencies" class="uri">https://www.kaggle.com/jessevent/all-crypto-currencies</a></p>
<p>##PREPARATION Libraries to install: tidyverse tidyr stringr broom lubridate ggplot2 zoo</p>
<p>#TIDYING THE DATA</p>
<pre class="r"><code>library(tidyverse)</code></pre>
<pre><code>## Registered S3 methods overwritten by &#39;ggplot2&#39;:
##   method         from 
##   [.quosures     rlang
##   c.quosures     rlang
##   print.quosures rlang</code></pre>
<pre><code>## Registered S3 method overwritten by &#39;rvest&#39;:
##   method            from
##   read_xml.response xml2</code></pre>
<pre><code>## -- Attaching packages --------------------------------- tidyverse 1.2.1 --</code></pre>
<pre><code>## v ggplot2 3.1.1       v purrr   0.3.2  
## v tibble  2.1.1       v dplyr   0.8.0.1
## v tidyr   0.8.3       v stringr 1.4.0  
## v readr   1.3.1       v forcats 0.4.0</code></pre>
<pre><code>## -- Conflicts ------------------------------------ tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<pre class="r"><code>library(stringr)
all_crypto &lt;- read_csv(&quot;crypto-markets.csv&quot;)</code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   slug = col_character(),
##   symbol = col_character(),
##   name = col_character(),
##   date = col_date(format = &quot;&quot;),
##   ranknow = col_double(),
##   open = col_double(),
##   high = col_double(),
##   low = col_double(),
##   close = col_double(),
##   volume = col_double(),
##   market = col_double(),
##   close_ratio = col_double(),
##   spread = col_double()
## )</code></pre>
<pre class="r"><code>all_crypto %&gt;%
  head()</code></pre>
<pre><code>## # A tibble: 6 x 13
##   slug  symbol name  date       ranknow  open  high   low close volume
##   &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt; &lt;date&gt;       &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
## 1 bitc~ BTC    Bitc~ 2013-04-28       1  135.  136. 132.  134.       0
## 2 bitc~ BTC    Bitc~ 2013-04-29       1  134.  147. 134   145.       0
## 3 bitc~ BTC    Bitc~ 2013-04-30       1  144   147. 134.  139        0
## 4 bitc~ BTC    Bitc~ 2013-05-01       1  139   140. 108.  117.       0
## 5 bitc~ BTC    Bitc~ 2013-05-02       1  116.  126.  92.3 105.       0
## 6 bitc~ BTC    Bitc~ 2013-05-03       1  106.  108.  79.1  97.8      0
## # ... with 3 more variables: market &lt;dbl&gt;, close_ratio &lt;dbl&gt;, spread &lt;dbl&gt;</code></pre>
<pre class="r"><code>ethereum_df &lt;- all_crypto%&gt;%
  filter(name == &quot;Ethereum&quot;)
ethereum_df%&gt;%head()</code></pre>
<pre><code>## # A tibble: 6 x 13
##   slug  symbol name  date       ranknow  open  high   low close volume
##   &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt; &lt;date&gt;       &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
## 1 ethe~ ETH    Ethe~ 2015-08-07       3 2.83  3.54  2.52  2.77  1.64e5
## 2 ethe~ ETH    Ethe~ 2015-08-08       3 2.79  2.8   0.715 0.753 6.74e5
## 3 ethe~ ETH    Ethe~ 2015-08-09       3 0.706 0.880 0.629 0.702 5.32e5
## 4 ethe~ ETH    Ethe~ 2015-08-10       3 0.714 0.730 0.637 0.708 4.05e5
## 5 ethe~ ETH    Ethe~ 2015-08-11       3 0.708 1.13  0.663 1.07  1.46e6
## 6 ethe~ ETH    Ethe~ 2015-08-12       3 1.06  1.29  0.884 1.22  2.15e6
## # ... with 3 more variables: market &lt;dbl&gt;, close_ratio &lt;dbl&gt;, spread &lt;dbl&gt;</code></pre>
<p>Now we gather all the historic data about Ethereum, we need to pick the needed columns to analyze.</p>
<pre class="r"><code>ethereum_tidy&lt;-ethereum_df%&gt;%
  select(name,date,open,close,high,low,market,volume)
ethereum_tidy</code></pre>
<pre><code>## # A tibble: 1,211 x 8
##    name     date        open close  high   low    market  volume
##    &lt;chr&gt;    &lt;date&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
##  1 Ethereum 2015-08-07 2.83  2.77  3.54  2.52  166610555  164329
##  2 Ethereum 2015-08-08 2.79  0.753 2.8   0.715  45486894  674188
##  3 Ethereum 2015-08-09 0.706 0.702 0.880 0.629  42399573  532170
##  4 Ethereum 2015-08-10 0.714 0.708 0.730 0.637  42818364  405283
##  5 Ethereum 2015-08-11 0.708 1.07  1.13  0.663  64569288 1463100
##  6 Ethereum 2015-08-12 1.06  1.22  1.29  0.884  73645011 2150620
##  7 Ethereum 2015-08-13 1.22  1.83  1.97  1.17  110607192 4068680
##  8 Ethereum 2015-08-14 1.81  1.83  2.26  1.75  110672322 4637030
##  9 Ethereum 2015-08-15 1.8   1.69  1.88  1.57  102303608 2554360
## 10 Ethereum 2015-08-16 1.68  1.57  1.7   1.09   94901005 3550790
## # ... with 1,201 more rows</code></pre>
<p>By extracting the essential data, I found out that most of the data is tidy.</p>
<p>#EXPLORATORY DATA ANALYSIS Now than our data is tidy, I plot the basic line based on daily close price in relation to date.</p>
<pre class="r"><code>ethereum_tidy %&gt;%
  ggplot()+
  geom_line(aes(x=date,y=close))+
  xlab(&quot;Days&quot;)+
  ylab(&quot;close&quot;)+
  ggtitle(&quot;Ethereum Daily Close Price From 2015 - 2018&quot;)</code></pre>
<p><img src="CMSC320_Final_project_files/figure-html/plot-1.png" width="672" /></p>
<p>From the graph we obviously observe that at the end of 2017 to the start of 2018 is the year where Ethereum had its first huge price boost. Our goal here is to analyze why this would happen and determine how important these factors are.</p>
<p>Let’s look at decomposition of the date to see if any other trends occur. For this purpose, we’ll be using decomposition method, see more details here: <a href="https://www.rdocumentation.org/packages/stats/versions/3.6.0/topics/decompose" class="uri">https://www.rdocumentation.org/packages/stats/versions/3.6.0/topics/decompose</a> However, to do decomposition we must first go over a metric used in stock prediction called moving averages. Moving averages are averages calculated over a defined number of time periods for example in the code below we determine the moving averages(monthly)over the course of Ethereum’s trading history. More info about moving average: <a href="https://www.investopedia.com/terms/m/movingaverage.asp" class="uri">https://www.investopedia.com/terms/m/movingaverage.asp</a></p>
<pre class="r"><code>library(zoo)</code></pre>
<pre><code>## 
## Attaching package: &#39;zoo&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     as.Date, as.Date.numeric</code></pre>
<pre class="r"><code>ethereum_tidy_2 &lt;-ethereum_tidy %&gt;%
  #create a column for 30-day moving average
  mutate(mov_avg = rollmean(ethereum_tidy$close,30,fill = NA, align = &quot;right&quot;))%&gt;%
  select(name,date,open,close,high,market,low,mov_avg,volume)</code></pre>
<p>We know can compare moving average entries with basic data entries through line plot</p>
<pre class="r"><code>ethereum_tidy_2 %&gt;% ggplot(aes (x = date),color= factor() )+
                    geom_line(aes(y=close),color = &#39;black&#39;) +
                    geom_line(aes(y=mov_avg),color=&#39;blue&#39;) +
                    xlab(&quot;date&quot;) +
                    ylab(&quot;price in US dollars&quot;) +
                    ggtitle(&quot;Moving Average Comparison&quot;)</code></pre>
<pre><code>## Warning: Removed 29 rows containing missing values (geom_path).</code></pre>
<p><img src="CMSC320_Final_project_files/figure-html/moving%20compare-1.png" width="672" /> As we can see from the graph, black line represents daily data and blue represent monthly data growth. Towards the end of 2017, black line is above the blue line which means the daily growth is much faster than the monthly growth.</p>
<pre class="r"><code>#here we are generating a time series, for daily entries, our frequency here is 365.
x &lt;- ts(ethereum_tidy_2$mov_avg,start=c(2015,8),end=c(2018,5),frequency = 365)
#use dcompose method and plot the graph
de &lt;- decompose(x)
plot(de)</code></pre>
<p><img src="CMSC320_Final_project_files/figure-html/decomposition-1.png" width="672" /> Observed from the decomposition graph, the trend is increasing over time. I also noticed the cyclic seasonality of the trend. But simply observe the trend over time isn’t that useful when it comes to something as volatile as the price of cryptocurrency, We must also look at other factors.</p>
<p>The plot indicates that there may be a correlation between price and other factors out there, maybe the volume?</p>
<pre class="r"><code>ethereum_tidy_2 %&gt;% 
              ggplot(aes(x=date,y=volume))+
              geom_line() +
              ##formatting to display correct labels
              scale_y_continuous(labels = scales::comma)</code></pre>
<p><img src="CMSC320_Final_project_files/figure-html/market-1.png" width="672" /> Clearly from the graph, there is a similarity between the volume and the closing price.</p>
<p>##LINEAR REGRESSION MODEL ANALYSIS To show whether there is a correlation betwen volume and closing price, we are going to build a linear regression model, which is a good method to test the correlation between two factors.</p>
<p>Null hypothesis: There is no correlation between volume and closing price</p>
<pre class="r"><code>lr &lt;- lm(close~volume,data =ethereum_tidy_2)
broom::tidy(lr)</code></pre>
<pre><code>## # A tibble: 2 x 5
##   term            estimate     std.error statistic  p.value
##   &lt;chr&gt;              &lt;dbl&gt;         &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept) 46.3         4.67               9.92 2.33e-22
## 2 volume       0.000000196 0.00000000309     63.3  0.</code></pre>
<p>According to the data, there is an increase of price per year and there is an increase of about 4.629297e+01 in close price per volume trade increase. Because there is an increase of volume by 1.955865e-07 with respect of close price, p value is zero, thus we reject it.</p>
<p>We would also like to fit a linear regression model for moving average with volume Null hypothesis: There is no correlation between volume and moving average</p>
<pre class="r"><code>lr2 &lt;- lm(mov_avg ~ volume,data=ethereum_tidy_2)
broom::tidy(lr2)</code></pre>
<pre><code>## # A tibble: 2 x 5
##   term            estimate     std.error statistic   p.value
##   &lt;chr&gt;              &lt;dbl&gt;         &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
## 1 (Intercept) 59.1         5.57               10.6 3.39e- 25
## 2 volume       0.000000180 0.00000000364      49.4 1.29e-289</code></pre>
<p>From the outcome, there is an increase of about 5.913842e+01 in moving average per volume trade increase. Because there is an increase of volume by 1.800868e-07 with respect of moving average,and p value is 1.286342e-289, thus we reject it.</p>
<p>More information about broom::tidy() and how to interpret the outcome: <a href="https://cran.r-project.org/web/packages/broom/vignettes/broom.html" class="uri">https://cran.r-project.org/web/packages/broom/vignettes/broom.html</a></p>
<p>As we build two linear regression models, we would also like to see how well tow models fit the data. I decided to Use the anova function to perform an F-test that compares two models.</p>
<p>More information about F-test and anova function can be found in these links: <a href="https://www.statmethods.net/stats/anova.html" class="uri">https://www.statmethods.net/stats/anova.html</a> <a href="https://www.rdocumentation.org/packages/stats/versions/3.6.0/topics/anova" class="uri">https://www.rdocumentation.org/packages/stats/versions/3.6.0/topics/anova</a></p>
<pre class="r"><code>lr_f&lt;-anova(lr)
lr2_f&lt;-anova(lr2)
lr_f</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: close
##             Df   Sum Sq  Mean Sq F value    Pr(&gt;F)    
## volume       1 71875663 71875663    4009 &lt; 2.2e-16 ***
## Residuals 1209 21675452    17928                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>lr2_f</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: mov_avg
##             Df   Sum Sq  Mean Sq F value    Pr(&gt;F)    
## volume       1 60234119 60234119  2441.6 &lt; 2.2e-16 ***
## Residuals 1180 29110343    24670                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>By looking at the table, because the residual sum in the mov_avg - volume model is smaller (1180), it indicates that it does a better job of fitting the estimate to the actual data then just using the close price data with the volume as a variable, where residual sum is larger (1209).</p>
<pre class="r"><code>ethereum_tidy_2 %&gt;% 
  ggplot(aes(x=volume,y=mov_avg)) +
  geom_point() +
  geom_smooth(method =lm) +
  scale_colour_gradient(low = &quot;black&quot;, high =&quot;blue&quot;)+
  scale_x_continuous(labels = scales::comma) +
  ggtitle(&quot;moving average over volume&quot;)</code></pre>
<pre><code>## Warning: Removed 29 rows containing non-finite values (stat_smooth).</code></pre>
<pre><code>## Warning: Removed 29 rows containing missing values (geom_point).</code></pre>
<p><img src="CMSC320_Final_project_files/figure-html/plot%20of%20linear%20model-1.png" width="672" /></p>
<p>By looking at the graph, it indicates that there is definitely a correlation between volume and moving average, also the blue fitted line has a nonzero slope, which in suggests that changes in the volume are associated with changes in the moving average. However, fitted line plots can only display the results from simple regression, which is one predictor variable and the response.</p>
<pre class="r"><code>summarized_lr2 &lt;- lr2%&gt;%summary()
summarized_lr2</code></pre>
<pre><code>## 
## Call:
## lm(formula = mov_avg ~ volume, data = ethereum_tidy_2)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -876.46  -58.32  -50.21   58.23  563.24 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 5.914e+01  5.572e+00   10.61   &lt;2e-16 ***
## volume      1.801e-07  3.645e-09   49.41   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 157.1 on 1180 degrees of freedom
##   (29 observations deleted due to missingness)
## Multiple R-squared:  0.6742, Adjusted R-squared:  0.6739 
## F-statistic:  2442 on 1 and 1180 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>We must also check the p-value which is significantly less than the standard significance level at 0.05.</p>
<p>Therefore, we can say there is a correlation between volumn and moving average.</p>
<p>##CONCLUSION Overall, this document introduces the baisc concepts of data manipulation and performing hypothesis testing. I am able to determine the correlation between volume and the moving average. The increase in volume affected the moving average as there was a crazy rise in price of Ethereum starting at the second half of 2017.</p>
<p>##Reference Dataset:<a href="https://www.kaggle.com/jessevent/all-crypto-currencies" class="uri">https://www.kaggle.com/jessevent/all-crypto-currencies</a> Data decomposition: <a href="https://www.rdocumentation.org/packages/stats/versions/3.6.0/topics/decompose" class="uri">https://www.rdocumentation.org/packages/stats/versions/3.6.0/topics/decompose</a> Moving average:<a href="https://www.investopedia.com/terms/m/movingaverage.asp" class="uri">https://www.investopedia.com/terms/m/movingaverage.asp</a> Broom documentation: <a href="https://cran.r-project.org/web/packages/broom/vignettes/broom.html" class="uri">https://cran.r-project.org/web/packages/broom/vignettes/broom.html</a> Anova: <a href="https://www.statmethods.net/stats/anova.html" class="uri">https://www.statmethods.net/stats/anova.html</a> ‘anova’ documentation: <a href="https://www.rdocumentation.org/packages/stats/versions/3.6.0/topics/anova" class="uri">https://www.rdocumentation.org/packages/stats/versions/3.6.0/topics/anova</a></p>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
